server:
  port: 8081

spring:

  sql:
    init:
      mode: always

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/despachos
    username: postgres
    password: admin123

logging:
  level:
    org.springframework.r2dbc: DEBUG